---
title: "faraway-glm-chap1-intro.Rmd"
author: "Robesyn"
date: "25 February 2017"
output:
  html_document: default
  word_document: default
---

Code Faraway GLM - chapter Introduction

```{r packages, echo=F}
library(tidyverse)
library(faraway)
library(forcats)
library(ggalt)
library(hrbrthemes)
```

```{r inspect}
head(gavote)
help(quantile)
help.search("quantiles")
glimpse(gavote)
summary(gavote)
```

Per county (=rows)
```{r undercount per county} 
gavote <- gavote %>% mutate(undercount = (ballots - votes)/ballots)
summary(gavote$undercount)
```


Note this is different than overall, for all counties together
```{r undercount overall}
overall <- gavote %>% summarize(sumdiff = sum(ballots-votes), sum = sum(ballots), proportionUndervotes = round(sumdiff/sum,3) )
overall$proportionUndervotes
```

```{r}
gavote %>% ggplot(aes(undercount)) +
               geom_histogram() +
               ggtitle("Undercount") +
               xlab("Percent Undercount")
```

```{r}
gavote %>% ggplot(aes(undercount)) + 
               geom_histogram(binwidth = 0.01)   
```

```{r}
gavote %>% ggplot(aes(undercount)) +
               geom_histogram(bins=10, fill="violet") +
               ggtitle("Undercount") +
               xlab("Percent Undercount") +
               ylab("Count")
```

```{r}
plot(density(gavote$undercount), main="Undercount") 
rug(gavote$undercount)
# base density plot gives bandwith of the kernel density (not in ggplot!)

# worked before but not anymore - plot.new 
```
```{r}
gavote %>% ggplot(aes(undercount)) +
               geom_density() +
               geom_rug() +
               ggtitle("Undercount") +
               xlab("Percent Undercount") +
               ylab("Count")   
## ggplot does not give bandwith and N of kernel density (even if I do not give xlab)
```

```{r value of max value}
max(gavote$undercount)  # idem as seen in summary
```

```{r}
levels(gavote$equip)
```

```{r for paper}
gavote %>% ggplot(aes(fct_rev(fct_infreq(equip)))) +
               geom_bar(fill="violet")+ 
               coord_flip() +
               ggtitle("Equipment frequencies") +
               xlab("Equipment") +
               ylab("Count") 
```

```{r for ppt}
gavote %>% ggplot(aes(fct_rev(fct_infreq(equip)))) +
               geom_bar(fill="violet")+ 
               coord_flip() +
               ggtitle("Equipment frequencies") +
               xlab("Equipment") +
               ylab("Count") + 
               
               theme_minimal() +
               
               theme( 
                              plot.title=element_text(size=25, face="bold"),
                              axis.title=element_text(size=20, face="bold"),
                              axis.text=element_text(size=18, face="bold"),
                              #panel.background = element_blank(),
                              plot.margin = margin(2,2,2,2)) +
               labs(
                              x = "\nEquipment\n",
                              y = "\nCount\n",
                              title="\nEquipment frequencies\n")  
```


```{r}
pie(table(gavote$equip), col=gray(0:4/4))
```
```{r}
gavote %>% ggplot(aes(equip, fill=econ)) +
               geom_bar()

gavote %>% ggplot(aes(equip, fill=econ)) +
               geom_bar(position="fill")
```
```{r}
gavote$pergore <- gavote$gore/gavote$votes 
plot(pergore ~ perAA, gavote, xlab="Proportion African American", ylab = "Proportion for Gore", pch=20, col="blue")
```
```{r}
gavote %>% ggplot(aes(equip, undercount)) + 
               geom_boxplot() 
```

```{r}
xtabs(~atlanta + rural, gavote)
```

```{r}
names(gavote)
```
```{r}
gavote <- gavote %>% rename(usage = rural)
names(gavote)
```

```{r}
nix <- gavote %>% select(perAA, ballots, undercount, pergore)
nix
```


```{r}
cor(nix)
```

```{r}
lmod <- lm(undercount ~ pergore + perAA, gavote)
lmod
coef(lmod)
```
```{r}
predict(lmod)
```

```{r}
residuals(lmod)
```
```{r}
# to visualise all four below results, first select chunk and then run

deviance(lmod)
df.residual(lmod)
nrow(gavote) - length(coef(lmod))
sqrt(deviance(lmod)/df.residual(lmod))  # residual standard error
```

```{r}
lmodsum <- summary(lmod)
lmodsum
lmodsum$sigma       # also residual standard error (see above)
lmodsum$r.squared
```

```{r}
lmodsum$r.squared
cor(predict(lmod),gavote$undercount)^2  
lmodsum$adj.r.squared
```

```{r}
lmod           # formula and coeff
coef(lmod)     # only coeff

summary(lmod)  # formula, coef, and residuals and Rsquared
```

```{r}
sumary(lmod) # coef, summary with n, p, residual SE, and Rsquared           # library(faraway)
```
```{r}
gavote$cpergore <- gavote$pergore - mean(gavote$pergore)
gavote$cperAA <- gavote$perAA - mean(gavote$perAA)
lmodi <- lm(undercount ~ cperAA + cpergore * usage + equip, gavote)
sumary(lmodi)
```

```{r}
anova(lmod, lmodi)
```

```{r}
drop1(lmodi, test="F")
```

```{r}
confint(lmodi)
```
```{r}
plot(lmodi)
```

```{r}
gavote[cooks.distance(lmodi) > 0.1,]
```

```{r}
halfnorm(hatvalues(lmodi))
```

```{r}
gavote[hatvalues(lmodi) > 0.3,]
```

```{r}
termplot(lmodi, partial = TRUE, terms = 1)
```

```{r}
library(MASS)
library(dplyr)  # to avoid masking of select by MASS package
rlmodi <- rlm(undercount ~ cperAA + cpergore * usage + equip, gavote)
summary(rlmodi)
```

```{r weighted least squares}
wlmodi <- lm(undercount ~ cperAA + cpergore * usage + equip, gavote, weights=ballots)
wlmodi
```

```{r}
sqrt(0.035*(1-0.035)/881)
```
```{r transformation}
plmodi <- lm(undercount ~ poly(cperAA, 4) + cpergore * usage + equip, gavote)
summary(plmodi)
```

```{r}
termplot(plmodi, partial = TRUE, terms = 1)
```

```{r}
library(splines)
blmodi <- lm(undercount ~ cperAA + bs(cpergore, 4) + usage + equip, gavote)
blmodi
```

```{r}
biglm <- lm(undercount ~ (equip + econ + usage + atlanta)^2 + (equip + econ + usage + atlanta)*(perAA + pergore), gavote)
biglm
```
```{r}
smallm <- step(biglm, trace=FALSE)
smallm
```
```{r}
drop1(smallm, test="F")
```

```{r}
finalm <- lm(undercount ~ equip + econ + perAA + equip:econ + equip:perAA, gavote)
finalm
summary(finalm)
```

```{r}
pdf <- data.frame(econ=rep(levels(gavote$econ), 5), equip=rep(levels(gavote$equip), rep(3,5)), perAA=0.233)
pdf

pp <- predict(finalm, new=pdf)
pp 
xtabs(round(pp, 3) ~ econ + equip, pdf)
```
```{r}
pdf <- data.frame(econ = rep("middle", 15), equip=rep(levels(gavote$equip), rep(3,5)), perAA=rep(c(.11, 0.23,0.35), 5))
pdf
pp <- predict(finalm, new=pdf)
pp
```

```{r}
propAA <- gl(3,1,15, labels=c("low","medium","high"))
xtabs(round(pp, 3) ~ propAA + equip,pdf)
```

## end chapter 1 ----



